apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/getsan4u/ibs-eks-argo-platform.git
    targetRevision: main
    path: platform/components/aws-load-balancer-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true