apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-workloads
  namespace: argocd
spec:
  description: Production workloads onboarded through platform templates

  sourceRepos:
    - https://github.com/getsan4u/*

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: external-secrets.io
      kind: ExternalSecret
    - group: external-secrets.io
      kind: SecretStore
    - group: monitoring.coreos.com
      kind: ServiceMonitor

  roles:
    - name: readonly
      description: Read-only access for app teams
      policies:
        - p, proj:prod-workloads:readonly, applications, get, prod-workloads/*, allow
